apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: application2
  name: application2
  namespace: application2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application2
  template:
    metadata:
      labels:
        app: application2
    spec:
      containers:
      - image: fmedery/techday-app2:0.2
        name: techday-app1
