apiVersion: v1
kind: Service
metadata:
  labels:
    app: application1
  name: application1
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  namespace: application1
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: application1
  type: LoadBalancer
