apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: application1
  name: application1
  namespace: application1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application1
  template:
    metadata:
      labels:
        app: application1
    spec:
      containers:
      - image: fmedery/techday-app1:0.2
        name: techday-app1
